### ISSUE TITLE
Problem while configuring.

### ISSUE THREAD

**Issue by anand-010** [ggodkin/openocd_RPI4#1]
Hai ggodkin.
I am new to embedded world.
I have a samd21g18a micro controller from microchip.
I am looking for a swd programmer and i am found openocd project.
I have a raspberry pi 4 8gb model. i am already tried different config files including this one none of them works.
I am installed openocd from this repo. clone git://git.code.sf.net/p/openocd/code openocd-code
from this instruction from a YouTube video.
https://drive.google.com/file/d/12dUwX3iibr3SfGeKsELKMJGjmPwc5aa9/view.

How would you installed opened on a rpi4.
Please guide me. I am a student and i don't have money to buy j-link.
Please help me. Thanks in advance.

the error that i am stuck now.
I am tested with raspberry pi pico swd pins and rpi4 gpio 25, 24, GND
```
pi@raspberrypi:~/bootloader $ sudo openocd
Open On-Chip Debugger 0.11.0+dev-00236-gcff0e417d-dirty (2021-06-29-15:00)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter srst delay' not 'adapter_nsrst_delay'
DEPRECATED! use 'adapter srst pulse_width' not 'adapter_nsrst_assert_width'
Info : BCM2835 GPIO JTAG/SWD bitbang driver
Info : clock speed 400 kHz
Error: Error connecting DP: cannot read IDR
```

Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections

**Comment by ggodkin** [comment]
Tell me little more about your installation and configuration. What configurations are you using and how do you connect your target device?

**Comment by anand-010** [comment]
Configuration.
usr/local/share/openocd/scripts/interface/rpi4.cfg
/home/pi/bootloader/openocd.cfg
i am used same config files from this repo.

I am installed it exactly like this.
https://drive.google.com/file/d/12dUwX3iibr3SfGeKsELKMJGjmPwc5aa9/view

I am thinking that it is an older or corrupted version of openocd.
Which repo did you used ? and is it works ?

I am connected gpio 25 to swdio 24 to swdclk (also tried wise versa) and gnd to gnd on the raspberry pi pico.

**Comment by anand-010** [comment]
Configuration.
usr/local/share/openocd/scripts/interface/rpi4.cfg
/home/pi/bootloader/openocd.cfg
i am used same config files from this repo.

I am installed it exactly like this.
https://drive.google.com/file/d/12dUwX3iibr3SfGeKsELKMJGjmPwc5aa9/view

I am thinking that it is an older or corrupted version of openocd.
Which repo did you used ? and is it works ?

I am connected gpio 25 to swdio 24 to swdclk (also tried wise versa) and gnd to gnd on the raspberry pi pico.

**Comment by anand-010** [comment]
I am also tried this repository too with fresh raspbian.
Same issue on it.
https://github.com/ntfreak/openocd
```
pi@raspberrypi:~/bootloader $ sudo openocd
Open On-Chip Debugger 0.11.0+dev-00236-gcff0e417d-dirty (2021-06-30-17:40)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter srst delay' not 'adapter_nsrst_delay'
DEPRECATED! use 'adapter srst pulse_width' not 'adapter_nsrst_assert_width'
Info : BCM2835 GPIO JTAG/SWD bitbang driver
Info : clock speed 400 kHz
Info : SWD DPIDR 0xdeadbeef

Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
```

**Comment by ggodkin** [comment]
I used openocd from the official site
Yes, I was able to program ARSAMD21... i.e upload the bootloader and started ti use USB port on ATSAMD xx for programming.
The configuration I used and posted on github is working only with RP4, not Pico.
your last post shows normal openocd response. 
Is your target chip properly configured, connected? did you install recommended capacitors on powerlines?

**Comment by anand-010** [comment]
I am used seeedstudio wio lite w600 as samd21 and also tried with raspberry pi pico.
Both of them not working (not showing chip details on "sudo openocd").
Have you give any params during the installtion.
I am give this ./configure --enable-sysfsgpio --enable-bcm2835gpio
Yes sure i am connected it properly.
It uses gpio 24 and 25 write?
If you have time would you like to give the steps.
Thank you.

**Comment by ggodkin** [comment]
I updated  [Readme](https://github.com/ggodkin/openocd_RPI4/issues) file with my steps to install.
GPIO are configured in one of config files I mentioned before. Can you share a link in a git to the config files you are using?

**Comment by anand-010** [comment]
After thousands of try.
I found this https://github.com/raspberrypi/openocd/issues/31
and it works on raspberry pi pico using a raspberry pi 4.
